---
swagger: "2.0"
info:
  version: "1.0.0"
  title: ARES Hasar Ekspertiz
  contact:
    email: destek@destechhasar.com
servers: [url: https://ares.rsservis.com.tr/ios_tablet_hasarv4_test]
schemes:
  - "https"
paths:
  /Login:
    post:
      tags:
        - Login User
      summary: Kullanıcı login servisi
      operationId: Login
      description: Kullanıcıyın login eder ve bilgilerini döner
      responses:
        "200":
          description: Status Ok
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Login"
        description: Login Ol
  /SetHasarEkspertiz:
    post:
      tags:
        - Hasar Ekspertiz
      summary: Hasar Ekspertiz Kaydı
      operationId: SetHasarEkspertiz
      description: Hasar ekspertiz bilgilerini kaydeder
      responses:
        "200":
          description: Status Ok
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetHasarEkspertiz"
        description: Hasar Ekspertiz Kaydı
  /ihaleyeCik:
    post:
      tags:
        - Parçaları İhaleye Çık
      summary: Parçaları ihaleye çıkarır
      operationId: ihaleyeCik
      description: Parçaları ihaleye çıkarır
      responses:
        "200":
          description: Status Ok
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ihaleyeCik"
        description: İhaleye Çık
components:
  schemas:
    Login:
      type: object
      required:
        - Kullanici
        - Sifre
      properties:
        Kullanici:
          type: string
          example: testkullanici
        Sifre:
          type: string
          format: password
          example: 12345
    SetHasarEkspertiz:
      type: object
      required:
        - AutHeader
        - OnarimNo
      properties:
        AutHeader:
          type: string
          example: uhmre1pbi78e6fnj9olvq9c5fm
        OnarimNo:
          type: string
          example: 688472
        HasarEkspertizBilgileri:
          type: array
          items:
            $ref: "#/components/schemas/hasarEkspertizBilgileri"
    ihaleyeCik:
      type: object
      required:
        - islem_ref_no
        - ihale_parcalar
      properties:
        islem_ref_no:
          type: string
          example: 688472
        ihale_parcalar:
          type: array
          items:
            $ref: "#/components/schemas/ihale_parcalar"
    ihale_parcalar:
      type: object
      required:
        - parca_ref_no
        - adet
      properties:
        parca_ref_no:
          type: string
          example: 688472
        adet:
          type: integer
          example: 1
    hasarEkspertizBilgileri:
      type: object
      required:
        - parca_ref_no
        - adet
      properties:
        ParcaGrubu:
          type: string
          example: Ön Tampon Grubu
        ParcaAdi:
          type: string
          example: Ön Tampon
        IsSiraNo:
          type: string
          example: 1
        Aciklama:
          type: string
          example: Kırılmış değişim gerekli
        OnarimTipi:
          type: string
          example: 0
        MontajTipi:
          type: string
          example: 0
        MontajTuruEski:
          type: string
          example: 0
        BoyaTipi:
          type: string
          example: 0
        OnarimTutar:
          type: string
          example: 150.0
        BoyaTutar:
          type: string
          example: 170.0
        BagliParcaSiraNo:
          type: string
          example: 2
        OnckMontajTuruRefNo:
          type: string
          example: 123
        ParcaKodu:
          type: string
          example: 4452
        ParcaTutar:
          type: string
          example: 120.5
        parcaAdedi:
          type: string
          example: 2
        kprtFyt:
          type: string
          example: 170.0
        mknkFyt:
          type: string
          example: 170.0
        elktFyt:
          type: string
          example: 170.0
        dsKlFyt:
          type: string
          example: 170.0
        camFyt:
          type: string
          example: 170.0
        PbFatura:
          type: string
          example: 2
        PbKayitId:
          type: string
          example: 232
        PbParcaID:
          type: string
          example: 2
        PbParcaTuru:
          type: string
          example: 3
